name: herbal_i
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: "3.3.4"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.0
  firebase_auth: ^4.18.0
  cloud_firestore: ^4.14.0
  firebase_database: ^10.3.1
  pinput: ^3.0.1
  animated_text_kit: ^4.2.2
  flutter_animate: ^4.2.0
  google_fonts: ^6.1.0
  logger: ^1.0.0
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.4
  permission_handler: 10.4.5
  camera: ^0.11.0
  tflite_flutter: ^0.10.4
  path_provider: ^2.1.2
  image: ^4.1.7
  email_auth: ^1.1.0
  pdf: ^3.10.4
  printing: ^5.12.0
  device_info_plus: ^9.0.3
  share_plus: ^7.2.1
  url_launcher: ^6.2.5
  firebase_storage: ^11.6.6
  intl: ^0.18.1
  fl_chart: ^0.66.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/best.tflite
    - assets/labels.txt
    - assets/plant_img/
    - assets/plants.json

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
